name: Build DEB and RPM Packages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Install dependencies for DEB & RPM
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm dpkg-dev build-essential fakeroot

      
      - name: Build .deb package
        run: |
            mkdir -p ~/build_deb/script-1.0-1.el8.noarch/DEBIAN
            cp debian/control ~/build_deb/script-1.0-1.el8.noarch/DEBIAN/control
            mkdir -p ~/build_deb/script-1.0-1.el8.noarch/usr/bin
            cp src/task1.sh ~/build_deb/script-1.0-1.el8.noarch/usr/bin/task1.sh
            chmod 755 ~/build_deb/script-1.0-1.el8.noarch/usr/bin/task1.sh
            dpkg-deb --build ~/build_deb/script-1.0-1.el8.noarch


      
      - name: Prepare RPM directories and archive
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          cp rpm/script.spec ~/rpmbuild/SPECS/
          mkdir script-1.0
          cp src/task1.sh script-1.0/task1  
          tar czf ~/rpmbuild/SOURCES/script.tar.gz script-1.0
          rm -rf script-1.0
      
      - name: Build .rpm package
        run: |
          rpmbuild -ba ~/rpmbuild/SPECS/script.spec

    
      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ~/build_deb/*.deb

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/**/*.rpm
